title: Tate Ward
email: tate@tatesworld.com
description: My personal website, mostly for fun.
baseurl: "" # Don't change this, this refers to the site's relative path, like /blog.
url: "MoonMoon2.github.io"
twitter_username: IhasNumNum
github_username:  MoonMoon2

# Build settings
#exclude: [vendor]
sass:
    style: compressed
exclude:
    - README.md
    - LICENSE.md
    - Gemfile
    - Gemfile.lock
    - package.json
include:
    - _pages
gems:
    - octopress-autoprefixer
