title: Tate's Site
email: tate@tatesworld.com
description:
baseurl: "" # Don't change this, this refers to the site's relative path, like /blog.
url: "https://tobiasaward.com"
github_username:  moonmoon2

# Build settings
#exclude: [vendor]
sass:
    style: compressed
exclude:
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - package.json
    - CODE_OF_CONDUCT.md
    - .gitignore
    - .vscode
include:
    - _pages
plugins:
    - octopress-autoprefixer

exiftag:

